name = "PhysicalParticles"
uuid = "78724250-4eb2-11e9-0f34-13a7aab864c5"
license = "GPLv3"
authors = ["islent <leoislent@gmail.com>"]
description = "Support for physical vectors and particles"
repository = "https://github.com/JuliaAstroSim/PhysicalParticles.jl"
version = "1.0.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[compat]
DocStringExtensions = "0.8"
NearestNeighbors = "0.4"
PhysicalConstants = "0.2"
Unitful = "0.18"
UnitfulAstro = "0.4, 1.0"
julia = "1.2.0"
