name: doc

on: [push]

# 64-bit Julia only
jobs:
  build:
    name: Documentation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: ['1.3.0']
        arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Install dependencies
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.update()'
      - name: Build and deploy
        env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Deploying to else where, so use SSH instead
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs --color=yes docs/make.jl